module.exports = {
  Allerton: 4,
  'Arden Heights': 1,
  Arrochar: 1,
  Arverne: 3,
  Astoria: 11,
  'Bay Ridge': 5,
  Baychester: 1,
  Bayside: 3,
  Bayswater: 5,
  'Bedford-Stuyvesant': 30,
  Bellerose: 1,
  Belmont: 6,
  Bensonhurst: 2,
  'Bergen Beach': 2,
  Bloomfield: 1,
  'Boerum Hill': 3,
  'Borough Park': 8,
  Briarwood: 2,
  'Brighton Beach': 5,
  'Bronx Park': 1,
  Bronxdale: 1,
  Brownsville: 10,
  Bushwick: 17,
  Canarsie: 6,
  'Carroll Gardens': 6,
  'Castle Hill': 1,
  'Castleton Corners': 1,
  'Central Park': 1,
  Chelsea: 11,
  Chinatown: 4,
  'Civic Center': 12,
  'Claremont Village': 12,
  Clifton: 1,
  'Clinton Hill': 3,
  'Co-op City': 2,
  'College Point': 2,
  Concourse: 6,
  'Concourse Village': 4,
  'Coney Island': 6,
  Corona: 3,
  'Crown Heights': 21,
  'Cypress Hills': 5,
  'Ditmars Steinway': 1,
  'Dongan Hills': 1,
  Douglaston: 1,
  'Downtown Brooklyn': 10,
  'Dyker Heights': 2,
  'East Elmhurst': 12,
  'East Flatbush': 17,
  'East Harlem': 34,
  'East Morrisania': 6,
  'East New York': 26,
  'East Village': 11,
  Edenwald: 2,
  Edgemere: 3,
  Elmhurst: 12,
  'Far Rockaway': 8,
  'Financial District': 1,
  Flatbush: 10,
  Flatlands: 2,
  Flushing: 16,
  Fordham: 22,
  'Forest Hills': 4,
  'Forest Park': 2,
  'Fort Greene': 6,
  'Fort Hamilton': 3,
  Glendale: 5,
  Gowanus: 2,
  Gramercy: 7,
  Graniteville: 4,
  Gravesend: 4,
  Greenpoint: 2,
  'Greenwich Village': 3,
  'Grymes Hill': 1,
  Harlem: 38,
  "Hell's Kitchen": 33,
  Highbridge: 3,
  'Howard Beach': 1,
  'Hunts Point': 4,
  Inwood: 10,
  'Jackson Heights': 5,
  Jamaica: 39,
  'Jamaica Estates': 2,
  Kensington: 4,
  'Kew Gardens': 3,
  'Kew Gardens Hills': 2,
  Kingsbridge: 9,
  'Kips Bay': 3,
  Laurelton: 1,
  'Long Island City': 5,
  Longwood: 20,
  'Lower East Side': 9,
  'Marble Hill': 2,
  Maspeth: 2,
  Melrose: 6,
  'Middle Village': 1,
  Midtown: 19,
  'Morningside Heights': 3,
  'Morris Heights': 3,
  'Morris Park': 7,
  Morrisania: 1,
  'Mott Haven': 10,
  'Mount Eden': 1,
  'Mount Hope': 5,
  'New Brighton': 1,
  'New Dorp': 4,
  'New Springville': 1,
  NoHo: 2,
  Norwood: 7,
  Olinville: 2,
  'Ozone Park': 9,
  'Park Hill': 2,
  'Park Slope': 1,
  Parkchester: 9,
  'Pelham Bay': 2,
  'Prospect-Lefferts Gardens': 5,
  'Queens Village': 8,
  "Randall's Island": 1,
  'Red Hook': 4,
  'Rego Park': 2,
  'Richmond Hill': 14,
  Ridgewood: 1,
  'Rockaway Beach': 2,
  'Rockaway Park': 1,
  Rosedale: 3,
  Rossville: 2,
  Schuylerville: 2,
  'Sea Gate': 1,
  'Sheepshead Bay': 12,
  'Shore Acres': 1,
  SoHo: 4,
  Soundview: 4,
  'South Ozone Park': 4,
  'South Slope': 2,
  'Springfield Gardens': 1,
  'St. Albans': 3,
  'St. George': 5,
  Stapleton: 3,
  Sunnyside: 5,
  'Sunset Park': 12,
  'Theater District': 8,
  'Throgs Neck': 9,
  'Todt Hill': 2,
  Tompkinsville: 1,
  Tottenville: 2,
  Tremont: 3,
  Tribeca: 5,
  'Two Bridges': 4,
  Unionport: 3,
  'University Heights': 5,
  'Upper East Side': 9,
  'Upper West Side': 19,
  'Van Nest': 1,
  Wakefield: 12,
  'Washington Heights': 18,
  'West Brighton': 1,
  'West Farms': 3,
  'West Village': 5,
  'Westchester Square': 1,
  Williamsbridge: 3,
  Williamsburg: 15,
  Woodhaven: 2,
  Woodlawn: 1,
  Woodrow: 1,
  Woodside: 4
}
