module.exports = {
  'Arden Heights': 3,
  Arrochar: 3,
  Arverne: 4,
  Astoria: 4,
  'Battery Park City': 2,
  Bayside: 4,
  Bayswater: 4,
  'Bedford-Stuyvesant': 8,
  'Belle Harbor': 5,
  Belmont: 23,
  Bensonhurst: 7,
  'Borough Park': 15,
  Brownsville: 2,
  "Bull's Head": 7,
  Bushwick: 7,
  'Cambria Heights': 1,
  Canarsie: 1,
  'Carroll Gardens': 4,
  Chelsea: 2,
  'Chelsea, Staten Island': 3,
  Chinatown: 4,
  'Claremont Village': 2,
  'Clinton Hill': 22,
  'Cobble Hill': 4,
  'College Point': 8,
  'Columbia St': 4,
  'Coney Island': 1,
  Corona: 10,
  'Crown Heights': 10,
  'Cypress Hills': 3,
  'Ditmars Steinway': 46,
  'Dongan Hills': 3,
  Douglaston: 6,
  'East Elmhurst': 17,
  'East Flatbush': 4,
  'East New York': 1,
  'East Village': 3,
  Edenwald: 4,
  Edgemere: 2,
  'Emerson Hill': 1,
  'Far Rockaway': 12,
  'Financial District': 2,
  Flatbush: 35,
  'Flatiron District': 3,
  Flatlands: 2,
  Flushing: 27,
  Fordham: 16,
  'Forest Hills': 39,
  'Fort Greene': 10,
  'Fort Hamilton': 6,
  'Fresh Meadows': 3,
  'Freshkills Park': 1,
  Glendale: 3,
  Gramercy: 4,
  'Grant City': 2,
  Gravesend: 13,
  'Great Kills': 4,
  Greenpoint: 20,
  'Greenwich Village': 3,
  Harlem: 4,
  "Hell's Kitchen": 10,
  Highbridge: 2,
  'Hollis Hills': 2,
  'Howard Beach': 3,
  Huguenot: 9,
  'Jackson Heights': 13,
  'Jamaica Estates': 5,
  Kensington: 4,
  'Kew Gardens': 19,
  Kingsbridge: 3,
  'Kips Bay': 6,
  Laurelton: 3,
  'Long Island City': 2,
  Longwood: 1,
  'Lower East Side': 11,
  'Manhattan Beach': 2,
  'Marine Park': 10,
  Maspeth: 1,
  'Midland Beach': 2,
  Midtown: 7,
  Midwood: 25,
  'Mill Basin': 2,
  'Morningside Heights': 13,
  'Morris Heights': 7,
  'Morris Park': 4,
  Morrisania: 1,
  'Mount Hope': 4,
  'Murray Hill': 7,
  Neponsit: 3,
  'New Dorp': 2,
  'New Springville': 2,
  Norwood: 4,
  Oakwood: 7,
  'Park Slope': 43,
  Parkchester: 4,
  "Prince's Bay": 5,
  'Prospect Heights': 3,
  'Prospect-Lefferts Gardens': 1,
  'Rego Park': 8,
  'Richmond Hill': 3,
  Richmondtown: 16,
  Ridgewood: 11,
  'Rockaway Beach': 2,
  'Rockaway Park': 13,
  Schuylerville: 1,
  'Sheepshead Bay': 16,
  'South Beach': 5,
  'South Slope': 6,
  'Springfield Gardens': 5,
  'St. Albans': 2,
  'Stuyvesant Town': 3,
  Sunnyside: 9,
  'Sunset Park': 3,
  'Theater District': 4,
  'Throgs Neck': 2,
  Tremont: 10,
  'Two Bridges': 1,
  'Upper East Side': 40,
  'Upper West Side': 59,
  Wakefield: 2,
  'Washington Heights': 2,
  'West Village': 10,
  Westerleigh: 2,
  Whitestone: 2,
  Williamsburg: 23,
  Woodhaven: 9,
  Woodrow: 6
}
