module.exports = {
  Allerton: 16,
  'Bath Beach': 7,
  'Bay Ridge': 2,
  'Bedford-Stuyvesant': 46,
  Belmont: 3,
  Bensonhurst: 5,
  'Borough Park': 4,
  'Brighton Beach': 1,
  Bronxdale: 7,
  Brownsville: 19,
  Bushwick: 61,
  Canarsie: 12,
  'Castle Hill': 7,
  'Central Park': 1,
  Chelsea: 15,
  Chinatown: 4,
  'Claremont Village': 2,
  Concourse: 7,
  'Concourse Village': 7,
  'Crotona Park': 1,
  'Crown Heights': 38,
  'East Flatbush': 40,
  'East Harlem': 32,
  'East Morrisania': 2,
  'East New York': 24,
  'East Village': 8,
  Edenwald: 3,
  Elmhurst: 1,
  'Far Rockaway': 8,
  Flatbush: 13,
  Flushing: 1,
  Fordham: 31,
  'Forest Hills': 6,
  Glendale: 8,
  Gravesend: 11,
  Greenpoint: 2,
  'Greenwich Village': 5,
  Harlem: 36,
  "Hell's Kitchen": 7,
  Highbridge: 21,
  Inwood: 13,
  Jamaica: 5,
  Kensington: 7,
  'Kew Gardens Hills': 9,
  Kingsbridge: 30,
  Longwood: 18,
  'Lower East Side': 1,
  'Marble Hill': 2,
  Melrose: 1,
  Midtown: 1,
  Midwood: 10,
  'Morris Heights': 12,
  Morrisania: 12,
  'Mott Haven': 2,
  'Mount Eden': 8,
  'Mount Hope': 25,
  'New Dorp Beach': 2,
  Nolita: 8,
  Norwood: 20,
  Olinville: 1,
  'Park Slope': 2,
  Parkchester: 23,
  'Pelham Bay': 4,
  'Prospect Heights': 6,
  'Prospect-Lefferts Gardens': 7,
  Ridgewood: 20,
  'Sheepshead Bay': 1,
  Soundview: 10,
  'South Slope': 39,
  'Sunset Park': 6,
  Tremont: 23,
  'University Heights': 28,
  'Upper East Side': 8,
  'Upper West Side': 15,
  'Van Nest': 7,
  Wakefield: 12,
  'Washington Heights': 46,
  'West Farms': 2,
  'West Village': 7,
  'Westchester Square': 2,
  Williamsbridge: 6,
  Williamsburg: 15
}
